# Generated by Django 5.2.5 on 2025-08-19 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_category', models.CharField(max_length=50)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('stock_exposure', models.JSONField(default=dict)),
                ('mf_exposure', models.JSONField(default=dict)),
                ('fd_value', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_profile',
            },
        ),
    ]
