# Generated by Django 5.2.5 on 2025-08-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_data', '0002_riskprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='calculation_mode',
            field=models.CharField(choices=[('zerodha', 'Zerodha'), ('manual', 'Manual')], default='zerodha', max_length=10),
        ),
    ]
