# Generated by Django 5.0.7 on 2025-08-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentSalary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yearsOfService', models.IntegerField()),
                ('employerType', models.CharField(max_length=100)),
                ('pensionScheme', models.CharField(max_length=100)),
                ('pensionBalance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employerContribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
