# Generated by Django 5.2.5 on 2025-08-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeexpectancy',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
