# Generated by Django 5.0.7 on 2025-08-18 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plannedRetirementAge', models.IntegerField()),
                ('retirementLifestyle', models.CharField(max_length=50)),
                ('monthlyRetirementExpense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('legacyGoal', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
