# Generated by Django 5.0.7 on 2025-08-20 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userdata_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='marital_status',
            new_name='maritalStatus',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='number_of_dependants',
            new_name='numberOfDependants',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AlterField(
            model_name='incomestatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retirementinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
